name: Deploy - Prod
run-name: Deploy Version ${{ github.ref_name }}

on:
  push:
    tags:
      - "v*"
  release:
    types:
      - created
  workflow_dispatch:
    inputs:
      administracao:
        type: boolean
        default: true
      teste2:
        type: boolean

jobs:        
  teste1:
    if: ${{ github.ref_name == 'develop' && github.event.inputs.administracao == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0
        name: Checkout
        
  teste2:
    if: ${{ github.ref_name == 'develop' && inputs.teste2 }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0
        name: Checkout
    
    
    
