name: Deploy - Prod
run-name: Deploy Version ${{ github.ref_name }}

on:
  workflow_call:
     
jobs:        
  develop:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      
      - run: echo "Rodando o workflow cd_deploy.yml"
        name: workflow call
        
        
#   notify:
#         name: Send Discord Notification
#         runs-on: ubuntu-latest
#         needs:
#           - develop
#           - alpha1
#         if: ${{ always() }}

#         steps:        
#           - name: Notify Deploy Develop
#             uses: nobrayner/discord-webhook@v1
#             with:
#               github-token: ${{ secrets.GITHUB_TOKEN }}
#               discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
#               color-success: '#30FA25'
#               color-failure: '#EB4034'
#               color-cancelled: '#808080'
    
    
    
