name: Deploy - Prod
run-name: Deploy Version ${{ github.ref_name }}

on:
  push:
    tags:
      - "v*"
  release:
    types:
      - created
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Selecione o ambiente para deploy
        options: 
        - develop
        - alpha1

jobs:        
  teste1:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0
        name: Checkout
        
  teste2:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0
        name: Checkout
    
    
    
