name: Deploy - Prod
run-name: Deploy Version ${{ github.ref_name }}

on:
  workflow_dispatch:
      inputs:
        Audit_api:
          description: Audit Api
          type: boolean
        audit_boletos:
          description: Audit Boletos
          type: boolean
        audit_novo_cliente:
          description: Audit Novo Cliente
          type: boolean
        audit_certidoes:
          description: Audit Certidoes
          type: boolean
        audit_navigationI:
          description: Audit NavigationI
          type: boolean
        auditI:
          description: AuditI
          type: boolean
        audit_editnewI:
          description: Audit EditnewI
          type: boolean
        audit_createnewI:
          description: Audit CreatenewI
          type: boolean
        audit_createnewButtons:
          description: Audit CreatenewButtons
          type: boolean
        audit_relacionados:
          description: Audit Relacionados
          type: boolean

jobs:        
  develop:
    if: github.event.inputs.environment == 'develop'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0
        name: Checkout
        
  alpha1:
    if: github.event.inputs.environment == 'alpha1'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0
        name: Checkout
        
        
  notify:
        name: Send Discord Notification
        runs-on: ubuntu-latest
        needs:
          - develop
          - alpha1
        if: ${{ always() }}

        steps:        
          - name: Notify Deploy Develop
            uses: nobrayner/discord-webhook@v1
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
              color-success: '#30FA25'
              color-failure: '#EB4034'
              color-cancelled: '#808080'
    
    
    
