name: Release condidata

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - run: echo "TAG=$(git tag --contains)"
        id: ref_tag
        name: get tag HEAD^
      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ steps.ref_tag.outputs.TAG }}
        name: Checkout

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
        name: Setup NodeJS

      - uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-node-${{ env.cache-name }}-
            ${{ runner.os }}-
        name: Cache node modules            

      - run: npm i
        name: Installing dependencies

      - uses: fregante/setup-git-user@v1
        name: setup git user
     
      - run: npm run release
        name: Create release candidate
