name: Release condidata

on:
  workflow_dispatch:

jobs:
  generate_release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: outro workflow
        uses: ./.github/workflows/cd_deploy.yml
        
#       - name: Get Latest Tag
#         id: latest_tag
#         uses: WyriHaximus/github-action-get-previous-tag@v1
        
#   release_create:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         shell: bash
#         working-directory: ./
#     needs: generate_release
#     steps:
#       - uses: actions/checkout@v3
#         with:
#            fetch-depth: 0
#            ref: ${{  needs.generate_release.outputs.current_tag }}
#         name: Checkout

#       - uses: actions/create-release@v1
#         name: Create Release
#         id: create_release
#         env:
#           GITHUB_TOKEN: ${{ secrets.TOKEN_AUTH }}
#         with:
#           tag_name: ${{ needs.generate_release.outputs.current_tag }}
#           release_name: ${{ needs.generate_release.outputs.current_tag }}
#           body: (CHANGELOG.md)
#           draft: false
#           prerelease: false
