name: Deploy - Prod

on:
  push:
    tags:
      - "v*"
  release:
    types: [created]

jobs:        
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0
        name: Checkout
