name: Deploy patch

on:
  workflow_dispatch:
    inputs:
      work_name:
        description: 'Adicione um nome para a execução (Patch ou Virada)'
        type: string
      type_work:
        required: true
        description: '(Patch ou Virada)'
        type: choice
        options: 
        - patch
        - virada

jobs:
  deploy:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./app
      steps:
        - uses: actions/checkout@v3
          name: Checkout
          
  greet:
    if: github.event.inputs.type_work == 'patch'
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./
    steps:
    - uses: actions/checkout@v3
      name: Checkout

    - uses: fregante/setup-git-user@v2
  
    - run: npm i
      name: Installing dependencies

    - run: npm run patch
      name: Deploying to patch

  create_release:
    if: github.event.inputs.type_work == 'patch'
    uses: ./.github/workflows/release.yml
