name: Teste

on:
  workflow_dispatch:


jobs:
  testevv:
    name: Release Create
    runs-on: ubuntu-latest
    steps:
      - run: echo "TAG=$(git tag --contains)"
        id: ref_tag
        name: get tag HEAD
      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ steps.ref_tag.outputs.TAG }}
        name: Checkout
        
      - run: git tag --contains
        name: exe git command check
      
      - run: |
          echo "${{ github.ref_name }}"
          echo "${{ github.ref_type }}"
        name: event object
          
