name: Teste

on:
  workflow_dispatch:


jobs:
  testevv:
    name: Release Create
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0
        name: Checkout
      
      - run: |
          echo "${{ github.ref_name }}"
          echo "${{ github.ref_type }}"
        name: event object
          
