name: Release condidata

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
#       - uses: fregante/setup-git-user@v1
#         name: setup git user
        
      - run: |
          echo "Done"
        name: Commands
