name: Deploy - Prod

on:
  push:
    tags:
      - "v*"
  release:
    types: [published]


jobs:
  deploy:
    name: deploy - prod
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src
    steps:
      - uses: actions/checkout@v2
        name: Checkout
          
run-name: Teste nome
