name: Release condidata

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - run: |
          echo "Done 2..."
        name: Commands
