name: Deploy - Prod
run-name: ${{ github.ref_name }}

on:
  push:
    tags:
      - "v*"
  workflow_run:
    workflows: [Release]
    types:
      - completed
      


jobs:   
  deploy:
    name: deploy - prod
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0
        name: Checkout
