name: Deploy - Prod

on:
  release:
    types: [published]


jobs:
  deploy:
    name: deploy - prod
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0
        name: Checkout
          
