name: Teste

on:
  workflow_dispatch:


jobs:
  release_create:
    name: Release Create
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v2
        name: Checkout
      
      - run: echo "${{ github.event }}"
        name: event object
          
