name: Release ${{ github.ref_name }}

on:
  push:
    tags:
      - "v*"
  workflow_run:
    workflows: [Release condidata]
    types:
      - completed


jobs:
  get_tag_current:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    outputs:
        current_tag: ${{ steps.latest_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0
        name: Checkout
        
      - name: Get Latest Tag
        id: latest_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        
  release_create:
    name: Create release ${{ needs.get_tag_current.outputs.current_tag }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    needs: get_tag_current
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0
           ref: ${{ needs.get_tag_current.outputs.current_tag }}
        name: Checkout
      
      - uses: actions/create-release@v1
        name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_AUTH }}
        with:
          tag_name: ${{ needs.get_tag_current.outputs.current_tag }}
          release_name: ${{ needs.get_tag_current.outputs.current_tag }}
          body: (CHANGELOG.md)
          draft: false
          prerelease: false
