name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
  workflow_run:
    workflows: [Release condidata]
    types:
      - completed

jobs:
  release_create:
    name: Release Create
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo "Tag: ${{ git tag --contains }}"
         
      - name: Get Latest Tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/create-release@v1
        name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_AUTH }}
        with:
          tag_name: ${{ steps.vars.outputs.current_tag }}
          release_name: ${{ steps.vars.outputs.current_tag}}
          body: (CHANGELOG.md)
          draft: false
          prerelease: false
