name: Release

on:
  create:

permissions:
  actions: read
  contents: read
  id-token: read
  pull-requests: read
  repository-projects: read



jobs:
  release_create:
    name: Release Create
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v2
        name: Checkout
        
      - name: Get Latest Tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        
      - uses: actions/create-release@v1
        name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_AUTH }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: (CHANGELOG.md)
          draft: false
          prerelease: false
