name: Release

on:
  push:
    tags:
      - "v*"
  workflow_run:
    workflows: [Release condidata]
    types:
      - completed

jobs:
  release_create:
    name: Release Create
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=current_tag::$(git tags --contains)"
          
      - run: |
          echo "Tag: ${{ steps.vars.outputs.current_tag }}"

      - uses: actions/create-release@v1
        name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_AUTH }}
        with:
          tag_name: ${{ steps.vars.outputs.current_tag }}
          release_name: ${{ steps.vars.outputs.current_tag}}
          body: (CHANGELOG.md)
          draft: false
          prerelease: false
