name: Release

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string

jobs:      
  release_create:
    name: Release Create
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/create-release@v1
        name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag_name }}
          release_name: Release ${{ inputs.tag_name }}
          body: Por favor, verifique o [CHANGELOG.md](https://github.com/Port-Louis/front/blob/master/CHANGELOG.md) para maiores detalhes.
          draft: false
          prerelease: false
