name: Release

on:
  push:
    tags:
      - "v*"
  workflow_run:
    workflows: [Release condidata]
    types:
      - completed

jobs:
  release_create:
    name: Release Create
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/create-release@v1
        name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_AUTH }}
        with:
          tag_name: ${{ GITHUB_REF#refs/tags/ }}
          release_name: ${{ GITHUB_REF#refs/tags/ }}
          body: (CHANGELOG.md)
          draft: false
          prerelease: false
