name: Release

on:
  push:
    tags:
      - "v*"
  workflow_run:
    workflows: [Release condidata]
    types:
      - completed


jobs:
  release_create:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0
           ref: ${{ steps.latest_tag.outputs.tag }}
        name: Checkout
      
      - name: Get Latest Tag
        id: latest_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - uses: actions/create-release@v1
        name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_AUTH }}
        with:
          tag_name: ${{ steps.latest_tag.outputs.tag }}
          release_name: ${{ steps.latest_tag.outputs.tag }}
          body: (CHANGELOG.md)
          draft: false
          prerelease: false
