name: Teste IF and Input

on:
  workflow_dispatch:
    inputs:
      deploy:
        type: choice
        description: Para qual ambiente quer fazer o deploy?
        options:
          - producao
          - alpha
        required: true

jobs:
  deploy:
    name: Test IF
    runs-on: ubuntu-latest
    steps:
    - name: prod
      if: ${{ github.event.inputs.deploy }} == 'producao'
      run: echo "${{ github.event.inputs.deploy }}"
    
    #- name: alpha
      #run: echo "alpha"
