name: Teste IF and Input

on:
  workflow_dispatch:
    inputs:
      production:
        type: boolean
        default: true
      homolog:
        type: boolean
        default: true
jobs:
  deploy_prod:
    if: github.event.inputs.production == 'true'
    name: Prod
    runs-on: ubuntu-latest
    steps:
    - name: prod
      run: echo "producao ${{ env.GITHUB_JOB_NAME }}"
      
  deploy_alpha:
    if: github.event.inputs.homolog == 'true'
    name: alpha
    runs-on: ubuntu-latest
    steps:
      - name: alpha
        run: echo "alpha ${{ env.GITHUB_JOB_NAME }}"
