name: Teste IF and Input

on:
  workflow_dispatch:
    inputs:
      production:
        type: boolean
        default: true
      homolog:
        type: boolean
        default: true
jobs:
  deploy_prod:
    if: github.event.inputs.production
    name: Test IF
    runs-on: ubuntu-latest
    steps:
    - name: prod
      run: echo "producao"
      
  deploy_alpha:
    if: github.event.inputs.homolog
    name: alpha
    runs-on: ubuntu-latest
    steps:
      - name: alpha
        run: echo "alpha"
