env:
  WORKFLOW_NAME: ${{ github.event.inputs.production == 'true' && 'prod' || 'homolog' }}

name: Teste IF and Input ${{ env.WORKFLOW_NAME }}

on:
  workflow_dispatch:
    inputs:
      production:
        type: boolean
        default: false
      homolog:
        type: boolean
        default: false

jobs:
  deploy_prod:
    if: github.event.inputs.production == 'true'
    name: Prod
    runs-on: ubuntu-latest
    steps:
    - name: prod
      run: echo "producao ${{ github.job }}"
      
  deploy_alpha:
    if: github.event.inputs.homolog == 'true'
    name: alpha
    runs-on: ubuntu-latest
    steps:
      - name: alpha
        run: echo "alpha ${{ github.job }}"
