name: Teste IF and Input

on:
  workflow_dispatch:
    inputs:
      deploy:
        type: choice
        description: Para qual ambiente quer fazer o deploy?
        options:
          - produção
          - alpha
        required: true

jobs:
  deploy:
    name: Test IF
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
      if: ${{ github.event.inputs.deploy }} == "produção"
    - name: prod
      run: echo "Produção"
    
    - name: alpha
      run: echo "alpha"
