name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Versão node: by default (16)'
        default: '16'
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v3
      with:
          node-version: "${{ github.event.inputs.tags }}"
          cache: 'npm'
          cache-dependency-path: './app/package-lock.json'
      name: Setup NodeJS
