name: Build and Test
on:
  workflow_dispatch:

jobs:
  build:
    name: Build the Code 1
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "build"
    # build job
  test:
    name: Test the Code 2
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Test"
    # test job
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: # make sure the notification is sent AFTER the jobs you want included have completed
      - build
      - test
    if: ${{ always() }} # You always want to be notified: success, failure, or cancelled
    
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.AUTH}}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color-success: '#4287f5'
          color-failure: 'eb4034'
          color-cancelled: '0x42daf5'
