name: Teste IF and Input

on:
  workflow_dispatch:
    inputs:
      produção:
        type: boolean
        default: true
      homolog:
        type: boolean
        default: true
jobs:
  deploy:
    if: github.event.inputs.deploy == 'producao'
    name: Test IF
    runs-on: ubuntu-latest
    steps:
    - name: prod
      run: echo "producao"
      
  deploy_alpha:
    if: github.event.inputs.deploy == 'alpha'
    name: alpha
    runs-on: ubuntu-latest
    steps:
      - name: alpha
        run: echo "alpha"
