name: work

on:
  workflow_run:
    workflows: [Release condidata]
    types: [completed]
    branches: [develop]
    

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:

      - run: |
          echo "Done..."
        name: Commands
